fixtures:
  repositories:
    facts: 'git://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'git://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    stdlib: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
    translate: 'git://github.com/puppetlabs/puppetlabs-translate.git'
    waffle_provision: 'git://github.com/puppetlabs/waffle_provision.git'
  symlinks:
    concat: '#{source_dir}'
